import { JOB_SORT_OPTIONS, JOB_STATUSES, JOB_TYPES } from 'enums';

export const API_TIME_OUT = 30000;

export const JOB_STATUS_LIST = [
  JOB_STATUSES.INTERVIEW,
  JOB_STATUSES.PENDING,
  JOB_STATUSES.DECLINED,
];

export const JOB_TYPE_LIST = [
  JOB_TYPES.FULL_TIME,
  JOB_TYPES.PART_TIME,
  JOB_TYPES.REMOTE,
  JOB_TYPES.INTERNSHIP,
];

export const JOB_SORT_OPTION_LIST = [
  JOB_SORT_OPTIONS.NAME_A,
  JOB_SORT_OPTIONS.NAME_Z,
  JOB_SORT_OPTIONS.LATEST,
  JOB_SORT_OPTIONS.OLDEST,
];
